### ISSUE TITLE
Docker container status is not right

### ISSUE THREAD

**Issue by dmitryos** [r4ven-me/openconnect#1]
Hi, when I start the container the status shows Starting... for a long time and then changes to Unhealthy... Could be script issue? Wondering if you have the same issue.
Cheers, Dmitry

**Comment by r4ven-me** [comment]
> Hi, when I start the container the status shows Starting... for a long time and then changes to Unhealthy... Could be script issue? Wondering if you have the same issue. Cheers, Dmitry

Hello!
Need more information. Tell me, do you use a domain name when running ocserv? Or are you using IP only?
A similar problem may appear if you are trying to start a container to obtain a domain name (certbot is launched first), and if it starts with an error, then the entire service does not start.

Have you made changes to docker-compose.yml or ocserv.conf? excluding parameters such as IP.

**Comment by dmitryos** [comment]
Hey! Yep - I'musing my already issued certificate. I don't use certbot and didn't make changes to the config files. I also have to say that the oc server works perfectly as a vpn while showing Unhealthy status in docker...
Cheers!

**Comment by r4ven-me** [comment]
> Hey! Yep - I'musing my already issued certificate. I don't use certbot and didn't make changes to the config files. I also have to say that the oc server works perfectly as a vpn while showing Unhealthy status in docker... Cheers!

Could you please send the "docker logs" output when the container starts or a screenshot of the error?
"Unhealthy" most likely indicates an unsuccessful "HEALTHCHECK", which was specified when building the image:
https://github.com/r4ven-me/openconnect/blob/main/src/server/Dockerfile
If this is critical, try rebuilding the image without this directive.
Best regards!

**Comment by dmitryos** [comment]
Just in case below is the startup log (which looks to me ok-ish):
---------------------------------------------
Starting OpenConnect Server

note: vhost:default: setting 'certificate' as primary authentication method

note: the cisco-client-compat option implies select-group-by-url = true; enabling

note: setting 'file' as supplemental config option

listening (TCP) on 0.0.0.0:443...
--------------------------------------------

Starting:
![image](https://github.com/user-attachments/assets/5904fca7-fd06-4e23-9cf5-ed8277553873)

and then:
![image](https://github.com/user-attachments/assets/912e7d2d-9159-450a-8591-55b30156591e)

which causes:
![image](https://github.com/user-attachments/assets/cf34e742-b730-4c33-be32-05eb9a9ca5f7)


Looks like the name of the healthckeck file needs to be changed from ocserv-main to just ocserv

Cheers!!

**Comment by r4ven-me** [comment]
> Looks like the name of the healthckeck file needs to be changed from ocserv-main to just ocserv

Oh, I just now understood that you are talking about the ocserv version 1.3 build. As it turned out, in version [ocserv 1.1](https://github.com/r4ven-me/openconnect/blob/main/src/server/Dockerfile) the main process is called `ovserv-main`, and in version 1.3 it is simply called `ocserv`.
Made corrections to the repository: [8f8af5b](https://github.com/r4ven-me/openconnect/commit/8f8af5b86bb928ba73e7ad8fc4eadb2bc897e233). I also updated and pushed the docker image to hub.docker.com: [r4venme/openconnect:1.3](https://hub.docker.com/layers/r4venme/openconnect/v1.3/images/sha256-31f4614f6ee913b368c98a60b44cb9c514d1f7fca7a1b4c2802677b3244d8b78?context=repo)
Thank you for your attention.
Best regards!

**Comment by dmitryos** [comment]
Confirming the new image is working beautifully with your latest changes!! Thank you!!!
